version: 0.2

phases:
  build:
    commands:
      - mvn clean -U install
  post_build:
    commands:
      - mvn package
  artifacts:
    files:
      - gomeetdr-0.0.2.war
      - .ebextensions/**/*