version: 0.2

phases:
  build:
    commands:
      - mvn clean -U install
  post_build:
    commands:
      - mvn package
      - mv target/gomeetdr-0.0.2 ./
artifacts:
  files:
    - gomeetdr-0.0.2/**/*
  discard-paths: yes