version: 0.2

phases:
  build:
    commands:
      - mvn clean -U install
  post_build:
    commands:
      - mvn package
      - unzip target/gomeetdr-0.0.2.war -d directoryToExtractTo
      - pwd
artifacts:
  files:
      - '**/*'
  discard-paths: yes