version: 0.2

phases:
  build:
    commands:
      - mvn clean -U install
  post_build:
    commands:
      - mvn package
      - sudo apt-get install zip unzip
      - unzip target/gomeetdr-0.0.2.war -d /target/directoryToExtractTo/
artifacts:
  files:
      - /target/directoryToExtractTo/**/*
  discard-paths: yes