version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean -U -Pcheckstyle
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/gomeetdr-0.0.2.war