version: 0.2

phases:
  build:
    commands:
      - mvn clean -U install
  post_build:
    commands:
      - mvn package
      - mkdir directoryToExtractTo
      - jar xvf target/gomeetdr-0.0.2.war -C ./directoryToExtractTo
artifacts:
  files:
      - /directoryToExtractTo/**
  discard-paths: yes