version: 0.2

phases:
  build:
    commands:
      - mvn clean -U install
  post_build:
    commands:
      - mvn package
      - unzip target/gomeetdr-0.0.2.war -d directoryToExtractTo
artifacts:
  files:
      - '**/*'
  base-directory: directoryToExtractTo
  name: gomeetdr-$(date +%Y-%m-%d)